# Generated by Django 5.0.6 on 2024-05-29 09:16

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='', upload_to='package_images/'),
            preserve_default=False,
        ),
    ]
